#!/usr/bin/env bash
# install Nginx and make it start


sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

sudo service nginx start
sudo ufw allow 'Nginx HTTP'
