#!/usr/bin/env bash
# install Nginx and make it start


sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
new_string+="\n\n\terror_page 404 \/custom_404.html;"
new_string+="\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default

if [ "$(pgrep -c nginx)" -le 0 ]
then
	sudo service nginx start
else
	sudo service nginx restart
fi
