#!/usr/bin/env bash
#installs load balancer
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy
sudo apt-get install -y haproxy
echo "
frontend web-front
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    mode http
    server 307982-web-01 18.204.5.64:80 check
    server 299081-web-02 52.21.57.114:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy start
