#!/usr/bin/env bash
#installs load balancer

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > sudo tee -a /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 307982-web-01 18.204.5.64 check
   server 307982-web-02 52.21.57.114 check
" >> sudo tee -a /etc/haproxy/haproxy.cfg

service haproxy start
