#!/usr/bin/env bash
# tell a password story

while IFS=":" read -r un psswd uid gid unid hd cmd
do
	echo "The user $un is part of the $gid gang, lives in $hd and rides $cmd. $uid's place is protected by the passcode $psswd, more info about the user here: $unid"
done < "/etc/passwd"
