#!/usr/bin/env bash
# displays best school ten times
# displays bad luck for the 4th loop
# displays goodluck for the 8th

count=1

while [ $count -lt 11 ]
do
	if [ $count = 4 ]
	then
		echo "bad luck"
	elif [ $count = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
